### ISSUE TITLE
Intern team placement

### ISSUE THREAD

**Issue by AtharvaLarva** [CourtneyThurston/microsoft-internships#1]
Hi :)

I love your guide! I think one part of the guide is inaccurate. For SWE intern team placements, most interns **do** interview for a specific team or at least specific engineering group (Experiences & Devices, Cloud + AI, AI & Research)). When you receive an offer email (at least circa Fall 2018), the team placement is provided to you and you're locked in to it -- there is no team placement survey imo.

**Comment by talk2bryan** [comment]
Yes I agree, I was placed in a team when I received my offer letter this September and verified it with the recruiter who called to extend me the offer.

**Comment by CourtneyThurston** [comment]
Hi, thanks for your comments. Unfortunately, that is not always the case.

In many instances, students do not hear what team they are on until a week or two before the internship starts. Worse, many students show up never hearing what team they're on, and only find out the day-of (which happened to me all three internships, despite trying to get that information from recruiters who could not verify which team it would be). This past year, my team placement did actually change at my request (it changed from a nebulous "not your previous team" to "yes, we changed it to your previous team"), so requesting specific team(s) CAN [but often does not] work.

The lack of clear team matching at Microsoft is one of the main reasons students turn down offers, or are dissatisfied by their internship(s), so it is important to be transparent about these issues.

FYI -- the "on behalf of" listed in your offer letter is only the group Champ. Within a group, there are usually upwards of 15-20+ teams. The offer letter "on behalf of" does not tell you anything about where you will be placed (and in my case, my Champ actually wasn't in my group at all -- only Azure in general).

Microsoft team matching is, honestly, a mess, and your individual experiences are not representative of the general problems.

Best of luck.

**Comment by CourtneyThurston** [comment]
With that said, I will try to be clearer in the guide.

**Comment by CourtneyThurston** [comment]
Added some changes. Hope it helps folks. And sorry for the brusqueness; midterms got me fucked up.

**Comment by talk2bryan** [comment]
haha, I really enjoyed reading your guide, it helped put things in perspective and prep me for said interview. No worries here, good luck!
